CREATE TABLE USER(
   ID INTEGER PRIMARY KEY  AUTOINCREMENT NOT NULL,
   USERNAME           TEXT      NOT NULL,
   PASSWORD           TEXT      NOT NULL
);

INSERT INTO USER (USERNAME, PASSWORD)
VALUES ("admin", "admin"); 

CREATE TABLE PROJECT(
   ID INTEGER PRIMARY KEY  AUTOINCREMENT NOT NULL,
   TITLE           TEXT      NOT NULL,
   USER_ID         NUMBER    NOT NULL,
   FOREIGN KEY(USER_ID) REFERENCES USER(ID)
)