CREATE TABLE USER(
   ID INTEGER PRIMARY KEY  AUTOINCREMENT NOT NULL,
   USERNAME           TEXT      NOT NULL,
   PASSWORD           TEXT      NOT NULL
);

INSERT INTO USER (USERNAME, PASSWORD)
VALUES ("admin", "admin"); 